### ISSUE TITLE
ライセンスの確認

### ISSUE THREAD

**Issue by cfinucane** [uich/demo-jackson-csv-web#1]
もしよろしければ、MappingJackson2CsvHttpMessageConverterを自分のプロジェクトに使用させていただきたいと思いますので、ライセンスの確認をお願いします。自由に使ってよろしいでしょうか？

**Comment by uich** [comment]
@cfinucane 
丁寧にライセンスの確認をして頂きありがとうございます。ライセンスは特にありません。
個人で書いたサンプル的なコードですので、ご自由にお使いください:smile:

**Comment by cfinucane** [comment]
了解しました！ありがとうございます。
